version: '3'
services:
  master:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./redis.master.conf:/etc/redis.conf
    command: >
         /etc/redis.conf
  slave1:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    depends_on:
      - master
    volumes:
      - ./redis.slave.conf:/etc/redis.conf
    command: >
         /etc/redis.conf
  slave2:
    image: "redis:alpine"
    ports:
      - "6381:6379"
    depends_on:
      - master
    volumes:
      - ./redis.slave.conf:/etc/redis.conf
    command: >
         /etc/redis.conf
